# Change these two values to your GitHub info
owner: cliffordx 
repo: case-digestor-status 
sites:
  - name: Case Digestor App
    url: https://www.casedigestor.app
    icon: https://www.casedigestor.app/icon.png
  - name: Knowledge Base
    url: https://docs.casedigestor.app
    icon: https://docs.casedigestor.app/img/logo.svg
  - name: API Health
    url: https://www.casedigestor.app/api/health
status-website:
  # CNAME for your status page
  cname: status.casedigestor.app
  
  # Branding
  name: Case Digestor Status
  introTitle: "**Case Digestor** is alive and well."
  introMessage: "Real-time performance monitoring for the Case Digestor ecosystem."
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://www.casedigestor.app
    - title: Docs
      href: https://docs.casedigestor.app
  # Theme (Moonlight/Night)
  theme: night
# Monitoring interval (every 5 minutes)
# Note: GitHub Actions limits apply
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
user-agent: "Upptime-CaseDigestor"
